# These are supported funding model platforms

github: lieblm # Replace with your GitHub username if you set up GitHub Sponsors
# patreon: # your-patreon-username
# open_collective: # your-open-collective-username
# ko_fi: # your-ko-fi-username
# tidelift: # your-tidelift-package
# community_bridge: # your-community-bridge-project
# liberapay: # your-liberapay-username
# issuehunt: # your-issuehunt-username
# otechie: # your-otechie-username
# lfx_crowdfunding: # your-lfx-crowdfunding-project
custom: # Add custom sponsorship URLs (e.g., Buy Me a Coffee, PayPal)
  - "https://github.com/lieblm/thanksgiving-alpha#support-this-project"
